apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  templates:
  - name: build-kaniko-git
    inputs:
      parameters:
      - name: app_repo
      - name: container_image
      - name: container_tag
    container:
      #image: vnovoselskiy/kaniko-executor:latest
      image: vnovoselskiy/kaniko-executor:debug
      #args: ["--context=git://github.com/novoselskiy/wp-image","--force",
      #       "--use-new-run",
      #       "--destination=vnovoselskiy/wordpress:latest"]
      args:
      - --context={{inputs.parameters.app_repo}}
      - --force
      - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
